CREATE TABLE contracts (
    id SERIAL PRIMARY KEY,
    contract_number VARCHAR(50) NO NULL UNIQUE,
    agency_id INTEGER REFERENCES agencies(id),
    title VARCHAR(200) NOT NULL,
    description TEXT,
    contract_type VARCHAR(50) CHECK (contract_type IN ('service', 'freight', 'charter', 'other')),
    start_date DATE NOT NULL,
    end_date DATE,
    total_value DECIMAL (20,2),
    currencty VARCHAR(3) DEFAULT 'IDR',
    payment_terms TEXT,
    status VARCHAR (30) DEFAULT 'draft' CHECK (status IN ('draft', 'pending', 'approved', 'active', 'completed', 'cancelled', 'expired')),
    marketing_user_id INTEGER REFERENCES users(id),
    operations_user_id INTEGER REFERENCES users(id),
    finance_user_id INTEGER REFERENCES users(id),
    marketing_remarks TEXT,
    operations_remarks TEXT,
    finance_remarks TEXT,
    marketing_status VARCHAR(20) DEFAULT 'pending' CHECK (marketing_status IN ('pending', 'submitted', 'approved', 'rejected', 'cancelled')),
    operatins_status VARCHAR(20) DEFAULT 'pending' CHECK (marketing_status IN ('pending', 'submitted', 'processing', 'completed', 'cancelled')),
    finance__status VARCHAR(20) DEFAULT 'pending' CHECK (marketing_status IN ('pending', 'processing', 'completed', 'partially_paid', 'paid', 'overdue')),
    created_by INTEGER REFERENCES users(id),
    approved_by INTEGER REFERENCES users(id),
    approved_at TIMESTAMP,
    cancelled_by INTEGER REFERENCES users(id),
    cancelled_at TIMESTAMP
    cancelled_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);