CREATE TABLE financial_transactions (
    id SERIAL PRIMARY KEY,
    transaction_number(50) NOT NULL UNIQUE,
    contract_id INTEGER REFERENCES contracts(id),
    shipment_id INTEGER REFERENCES contracts(id),
    agency_id INTEGER REFERENCES agencies(id),
    transaction_type VARCHAR(30) NOT NULL CHECK (transaction_type IN ('invoice', 'payment', 'credit_note', 'advance', 'refund')),
    invoice_id INTEGER,
    amount DECIMAL (15,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'IDR',
    exchange_rate DECIMAL(10,6) DEFAULT 1.000000,
    amount_local DECIMAL (15,2),
    due_date DATE,
    payment_date DATE,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'issued', 'partially_paid', 'paid', 'overdue', 'cancelled', 'refunded')),
    payment_method VARCHAR(30) CHECK (payment_method IN ('bank_transfer', 'credit_card', 'check', 'online_payment')),
    reference_number VARCHAR(100),
    description TEXT,
    notes TEXT,
    tax_amount DECIMAL(15,2) DEFAULT 0.00,
    tax_rate DECIMAL(5,2) DEFAULT 0.00,
    discount_amount DECIMAL (15,2) DEFAULT 0.00,
    total_amount DECIMAL (15,2) DEFAULT 0.00M
    created_by INTEGER REFERENCES users(id),
    approved_by INTEGER REFERENCES users(id),
    approved_at TIMESTAMP,
    cancelled_by INTEGER REFERENCES users(id),
    cancelled_at TIMESTAMP,
    cancelled_reason TEXT,
    reminder_sent BOOLEAN DEFAULT FALSE,
    reminder_count INTEGER DEFAULT 0,
    last_reminder_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);