CREATE TABLE shipments (
    id SERIAL PRIMARY KEY,
    shipment_number VARCHAR(50) NOT NULL UNIQUE,
    contract_id INTEGER REFERENCES contracts(id),
    agency_id INTEGER REFERENCES agencies(id),
    vessel_name VARCHAR(100),
    voyage_number VARCHAR(50),
    cargo_type VARCHAR(100),
    cargo_description TEXT,
    quantity DECIMAL(12,2),
    unit_of_measure VARCHAR(20),
    loading_port VARCHAR(100),
    discharge_port VARCHAR(100),
    loading_date DATE,
    discharge_date DATE,
    estimated_arrival DATE,
    actual_arrival DATE,
    status VARCHAR(30) DEFAULT 'planned' CHECK (status IN ('planned', 'in_transit', 'delayed', 'arrived', 'delivered', 'cancelled')),
    operations_remarks TEXT,
    marketing_remarks TEXT,
    special_instructions TEXT,
    created_by INTEGER REFERENCES users(id),
    assigned_to INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);